//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCHOOLDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Result20
    {
        public string RollNumber { get; set; }
        public int PassingYear { get; set; }
        public string Grades { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
